package com.example.backend.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Response DTO for job offer recommendations.
 * 
 * This object is returned to the frontend when a candidate requests recommendations.
 * It contains all the job details plus the relevance score and reason why we recommend it.
 * 
 * Flow:
 * JobRecommendationService calculates scores → Creates RecommendationResponseDTO objects
 * → RecommendationController returns list of these objects as JSON to frontend
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class RecommendationResponseDTO {

    // ── Job Details ─────────────────────────────────────────────────────────

    /**
     * The database ID of the job offer.
     * Used if frontend needs to reference the job or apply to it.
     */
    private Long jobOfferId;

    /**
     * Job title - what the position is called.
     * Example: "Senior Java Developer", "Frontend Engineer"
     */
    private String title;

    /**
     * Full job description - what the job entails.
     * Usually long text describing responsibilities, company, etc.
     */
    private String description;

    /**
     * Job location - where the job is based.
     * Example: "Remote", "Paris, France", "New York, USA"
     */
    private String location;

    /**
     * Contract type - full-time, part-time, contract, etc.
     * Example: "FULL_TIME", "CONTRACT", "PART_TIME"
     */
    private String contractType;

    /**
     * Required skills - what skills the job is looking for.
     * Example: "Java, Spring Boot, MySQL, REST APIs"
     */
    private String requiredSkills;

    // ── Recommendation Scores ───────────────────────────────────────────────

    /**
     * Relevance score from 0 to 100.
     * 
     * How Google Gemini calculated this:
     * - 80-100: Excellent match (has most/all required skills)
     * - 60-79: Good match (has key skills, might need to learn some)
     * - 40-59: Fair match (related experience, transferable skills)
     * - <40: Poor match (not recommended)
     * 
     * This is used for sorting recommendations (highest score first).
     */
    private Double relevanceScore;

    /**
     * Why we recommend this job to the candidate.
     * 
     * Example reasons:
     * - "Strong match: You have 5+ years Spring Boot experience, job needs 3-5 years"
     * - "Good fit: Your React skills match the frontend requirements"
     * - "You have relevant database experience for this data engineer role"
     * 
     * Short, human-readable explanation generated by Google Gemini.
     */
    private String matchingReason;
}
